version: '3'

services:
    redis:
      image: redis
      ports:
        - "6379"
      networks:
        - mynet

    mongo:
      image: mongo
      volumes:
        - data:/data/db
      ports:
        - "27017"
      networks:
        - mynet

    signup:
      image: pclub/puppy-love:signup
      env_file:
        - .backend.env
      ports:
        - "3001"
      links:
        - mongo
        - redis
      networks:
        - mynet

    backend:
      image: pclub/puppy-love:backend
      env_file:
        - .backend.env
      ports:
        - "3000"
      links:
        - mongo
        - redis
        - signup
      networks:
        - mynet

    nginx:
      image: pclub/puppy-love:frontend
      ports:
        - "80:80"
      networks:
        - mynet
      links:
        - backend:backend
volumes:
  data:

networks:
    mynet:
