version: '3'

services:
    redis:
      image: redis
      ports:
        - "6379"
      networks:
        - mynet

    mongo:
      image: mongo
      volumes:
        - data:/data/db
      ports:
        - "27017"
      networks:
        - mynet

    signup:
      image: pclub/puppy-love:signup
      env_file:
        - .backend.env
        - .mail.env
      ports:
        - "3001"
      links:
        - mongo
        - redis
      networks:
        - mynet

    backend:
      image: pclub/puppy-love:backend
      env_file:
        - .backend.env
        - .pass.env
      environment:
        - VIRTUAL_HOST=pclub.cse.iitk.ac.in
        - VIRTUAL_PROTO=http
      ports:
        - "3000"
      links:
        - mongo
        - redis
        - signup
      networks:
        - mynet

    frontend:
      image: pclub/puppy-love:frontend
      ports:
        - "80"
      networks:
        - mynet
      environment:
        - VIRTUAL_HOST=pclub.cse.iitk.ac.in
        - VIRTUAL_PROTO=http

    nginx:
      image: pclub/puppy-love:nginx
      ports:
        - "80:80"
      environment:
        - VIRTUAL_PORT=3000;80
      networks:
        - mynet
      links:
        - backend
        - frontend
volumes:
  data:

networks:
    mynet:
